export default [
  {code: "CS 6035", name: "Introduction to Information Security"},
  {code: "CS 6210", name: "Advanced Operating Systems"},
  {code: "CSE 6220", name: "Intro to High-Performance Computing"},
  {code: "CSE 6242", name: "Data and Visual Analytics"},
  {code: "CS 6250", name: "Computer Networks"},
  {code: "CS 6262", name: "Network Security"},
  {code: "CS 6290", name: "High Performance Computer Architecture"},
  {code: "CS 6300", name: "Software Development Process"},
  {code: "CS 6310", name: "Software Architecture and Design"},
  {code: "CS 6340", name: "Software Analysis and Test"},
  {code: "CS 6400", name: "Database Systems Concepts and Design"},
  {code: "CS 6440", name: "Intro to Health Informatics"},
  {code: "CS 6460", name: "Educational Technology"},
  {code: "CS 6475", name: "Computational Photography"},
  {code: "CS 6476", name: "Computer Vision"},
  {code: "CS 6505", name: "Computability, Complexity and Algorithms"},
  {code: "CS 6601", name: "Artificial Intelligence"},
  {code: "CS 6750", name: "Human-Computer Interaction"},
  {code: "CS 7637", name: "Knowledge-Based Artificial Intelligence: Cognitive Systems"},
  {code: "CS 7641", name: "Machine Learning"},
  {code: "CS 7646", name: "Machine Learning for Trading"},
  {code: "CSE 8803", name: "Special Topics: Big Data for Health Informatics"},
  {code: "CS 8803-001", name: "Artificial Intelligence for Robotics"},
  {code: "CS 8803-002", name: "Introduction to Operating Systems"},
  {code: "CS 8803-003", name: "Special Topics: Reinforcement Learning"},
  {code: "CS 8803-004", name: "Special Topics: Embedded Software"},
  {code: "CS 8803", name: "O07 Special Topics: Cyber-Physical Systems Security"},
]