export default [
  {code: 'CS 6035', name: 'Introduction to Information Security'},
  {code: 'CS 6210', name: 'Advanced Operating Systems'},
  {code: 'CSE 6140', name: 'Computational Science and Engineering Algorithms'},
  {code: 'CSE 6220', name: 'Intro to High-Performance Computing'},
  {code: 'CSE 6242', name: 'Data and Visual Analytics'},
  {code: 'CS 6250', name: 'Computer Networks'},
  {code: 'CS 6262', name: 'Network Security'},
  {code: 'CS 6235', name: 'Real Time Systems'},
  {code: 'CS 6238', name: 'Secure Computer Systems'},
  {code: 'CS 6260', name: 'Applied Cryptography'},
  {code: 'CS 6365', name: 'Introduction to Enterprise Computing'},
  {code: 'CS 6422', name: 'Database System Implementation'},
  {code: 'CS 6675', name: 'Advanced Internet Computing Systems and Applications'},
  {code: 'CS 7210', name: 'Distributed Computing'},
  {code: 'CS 7260', name: 'Internetworking Architectures and Protocols'},
  {code: 'CS 7270', name: 'Networked Applications and Services'},
  {code: 'CS 7290', name: 'Advanced Topics in Microarchitecture'},
  {code: 'CS 7292', name: 'Reliability and Security in Computer Architecture'},
  {code: 'CS 7560', name: 'Theory of Cryptography'},
  {code: 'CS 7620', name: 'Case-Based Reasoning'},
  {code: 'CS 6465', name: 'Computational Journalism'},
  {code: 'CS 7634', name: 'AI Storytelling in Virtual Worlds'},
  {code: 'CS 7632', name: 'Game AI'},
  {code: 'CS 7650', name: 'Natural Language'},
  {code: 'CS 6795', name: 'Introduction to Cognitive Science'},
  {code: 'CS 7610', name: 'Modeling and Design'},
  {code: 'CS 7510', name: 'Graph Algorithms'},
  {code: 'CSE 6740', name: 'Computational Data Analysis: Learning, Mining, and Computation'},
  {code: 'CS 7540', name: 'Spectral Algorithms'},
  {code: 'CS 7545', name: 'Machine Learning Theory'},
  {code: 'CS 7616', name: 'Pattern Recognition'},
  {code: 'CSE 6240', name: 'Web Search and Text Mining'},
  {code: 'CS 6520', name: 'Computational Complexity Theory'},
  {code: 'CS 6550', name: 'Design and Analysis of Algorithms'},
  {code: 'CS 7520', name: 'Approximation Algorithms'},
  {code: 'CS 7530', name: 'Randomized Algorithms'},
  {code: 'CS 6290', name: 'High Performance Computer Architecture'},
  {code: 'CS 6300', name: 'Software Development Process'},
  {code: 'CS 6310', name: 'Software Architecture and Design'},
  {code: 'CS 6340', name: 'Software Analysis and Test'},
  {code: 'CS 6400', name: 'Database Systems Concepts and Design'},
  {code: 'CS 6440', name: 'Intro to Health Informatics'},
  {code: 'CS 6460', name: 'Educational Technology'},
  {code: 'CS 6475', name: 'Computational Photography'},
  {code: 'CS 6476', name: 'Computer Vision'},
  {code: 'CS 6505', name: 'Computability, Complexity and Algorithms'},
  {code: 'CS 6601', name: 'Artificial Intelligence'},
  {code: 'CS 6750', name: 'Human-Computer Interaction'},
  {code: 'CS 7637', name: 'Knowledge-Based Artificial Intelligence: Cognitive Systems'},
  {code: 'CS 7641', name: 'Machine Learning'},
  {code: 'CS 7646', name: 'Machine Learning for Trading'},
  {code: 'CSE 8803', name: 'Special Topics: Big Data for Health Informatics'},
  {code: 'CS 8803-FPL', name: 'Special Topics: Foundations of Programming Languages'},
  {code: 'CS 8803-001', name: 'Artificial Intelligence for Robotics'},
  {code: 'CS 8803-002', name: 'Introduction to Operating Systems'},
  {code: 'CS 8803-003', name: 'Special Topics: Reinforcement Learning'},
  {code: 'CS 8803-004', name: 'Special Topics: Embedded Software'},
  {code: 'CS 8803-007', name: 'Special Topics: Cyber-Physical Systems Security'},
  {code: 'CS 8803-xx1', name: 'Special Topics: Computational Creativity'},
  {code: 'CS 8803-xx2', name: 'Special Topics: Computational Social Science'},
  {code: 'CS 8803-xx3', name: 'Special Topics: Advanced Game AI'},
  {code: 'CS 8803-xx4', name: 'Special Topics: Probabilistic Graph Models'},
  {code: 'CS 8803-xx5', name: 'Special Topics: Multiview Geometry in Computer Vision'},
]